GET http://localhost:5067/games

###

GET http://localhost:5067/games/1

###

POST http://localhost:5067/games
Content-Type: application/json

{
    "Name": "Mortal Kombat",
    "GenreId": 1,
    "Price": 80.99,
    "ReleaseDate": "1980-03-13"
}

###
PUT http://localhost:5067/games/2
Content-Type: application/json

{    
    "Id": 2,
    "Name": "John Wick",
    "GenreId": 1,
    "Price": 99.99,
    "ReleaseDate": "2022-09-19"
}

####

DELETE  http://localhost:5067/games/1

###


